# Generated by Django 5.0.4 on 2024-05-05 22:12

import app_photo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.ImageField(upload_to='images', validators=[app_photo.models.validate_file_size]),
        ),
    ]
